baseURL       : https://ncar.github.io/vast/
languageCode  : en-us
title         : "VAST | Visualization and Analysis Software and Technology"
theme         : roxo-hugo
enableGitInfo : true
summarylength : 25

menu:
  nav:
    - name      : About
      url       : about
      weight    : 1
    - name      : News
      url       : news
      weight    : 2
    - identifier: what
      name      : What we do
      weight    : 3
    - parent    : what
      name      : Software
      url       : software
      weight    : 1
    - parent    : what
      name      : Education
      url       : education
      weight    : 2
    - parent    : what
      name      : Services
      url       : services
      weight    : 3
    - parent    : what
      name      : R&D
      url       : rnd
      weight    : 4
    - name      : Publications
      url       : publications
      weight    : 4
    - name      : Contact Us
      url       : contact
      weight    : 10

# Site Params
params:
  logo: images/logos/ncar-vast-logo-navy.svg
  dateFormat: "26 FEB 1994"
  description: "VAST is the Visualization and Analysis Software and Technology section at the National Center for Atmospheric Research (NCAR)."
  author: "VAST"
  email: "vast@ucar.edu"

  projects:
    enable: true
    title: RECENT PROJECTS
    subtitle: Some of our most recent projects

  footer:
    contactInfo:
      title  : Contact Info
      address: 1850 Table Mesa Dr.<br>Boulder, CO 80305
      email  : vast@ucar.edu

    sitemap:
      title: Sitemap
      column:
        - link:
          - name: About us
            url : about
          - name: Blog
            url : blog
        - link:
          - name: Software
            url : software
          - name: Training
            url : training
          - name: Projects
            url : projects
          - name: Research
            url : projects
          - name: Services
            url : services

