baseURL       = "https://vast.ucar.edu/"
languageCode  = "en-us"
title         = "VAST | Visualization and Analysis Software Team"
theme         = "roxo-hugo"
summarylength = 25
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    identifier = "about"
    name       = "About Us"
    url        = "about"
    weight     = 1
  [[menu.nav]]
    parent     = "about"
    name       = "Mission"
    url        = "about/mission"
    weight     = 1
  [[menu.nav]]
    parent     = "about"
    name       = "Team"
    url        = "about/team"
    weight     = 2
  [[menu.nav]]
    identifier = "what"
    name    = "What we do"
    url     = "what-we-do"
    weight  = 2
  [[menu.nav]]
    parent  = "what"
    name    = "Software"
    url     = "software"
    weight  = 1
  [[menu.nav]]
    parent  = "what"
    name    = "Training"
    url     = "training"
    weight  = 2
  [[menu.nav]]
    parent  = "what"
    name    = "Projects"
    url     = "projects"
    weight  = 3
  [[menu.nav]]
    parent  = "what"
    name    = "Services"
    url     = "services"
    weight  = 4
  [[menu.nav]]
    name    = "Blog"
    url     = "blog"
    weight  = 3
  [[menu.nav]]
    name    = "Publications"
    url     = "publications"
    weight  = 4
  [[menu.nav]]
    name    = "Presentations"
    url     = "presentations"
    weight  = 5

# Site Params
[params]
  logo = "images/bam-crop.png"
  dateFormat = "26 FEB 1994"
  description = "VAST is the Visualization and Analysis Software Team at the National Center for Atmospheric Research (NCAR)."
  author = "VAST"
  # googleAnalitycsID = "Your ID"
  # formspreeFormUrl  = "https://formspree.io/myykjpje"
  email = "vast@ucar.edu"

  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Get in touch"
    url     = "contact"

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/NCAR-Waves.png"
    heading               = "The Data Assimilation Research Testbed"
    tagline               = "a community facility for ensemble data assimilation"
    primary_button        = "Research"
    primary_button_url    = "research"
    secondary_button      = "Contact Us"
    secondary_button_url  = "contact"
    animation             = "images/lorenz.mp4"

  [params.research]
    enable               = true
    title                = "RECENT PROJECTS"
    subtitle             = "Research projects involving DART"
    primary_button       = "Publications"
    primary_button_url   = "publications"
    secondary_button     = "Presentations"
    secondary_button_url = "presentations"

  [params.tutorial]
    background_image     = "images/backgrounds/NCAR-Waves.png"

  [params.call_to_action]
    enable              = false
    background_image    = "images/backgrounds/cta-background.jpg"
    heading             = "Tutorials"
    tagline             = "Geoscientists are generational thinkers. We study deep into the Earth's past and make projections of its future. DART provides training materials to guide the next generation of scientists."
    primary_button      = "Submit Query"
    primary_button_url  = "contact"
    secondary_button    = "Not Convinced"
    secondary_button_url = "research"

  [params.collab]
    enable           = true
    heading          = "Supported models"
    background_image = "images/backgrounds/NCAR-Waves.png"

  [params.footer]
    [params.footer.contactInfo]
      title   = "Contact Info"
      address = "1850 Table Mesa Dr.<br>Boulder, CO 80305"
      email   = "vast@ucar.edu"

      [params.footer.sitemap]
        title  = "Sitemap"
        [[params.footer.sitemap.link]]
          name = "About us"
          url  = "about"
        [[params.footer.sitemap.link]]
          name = "What we do"
          url  = "what-we-do"
        [[params.footer.sitemap.link]]
          name = "Blog"
          url  = "blog"
        [[params.footer.sitemap.link]]
          name = "Publications"
          url  = "publications"
        [[params.footer.sitemap.link]]
          name = "Presentations"
          url  = "presentations"

      [params.footer.research]
        title  = "What we do"
        [[params.footer.research.link]]
          name = "Software"
          url  = "software"
        [[params.footer.research.link]]
          name = "Training"
          url  = "training"
        [[params.footer.research.link]]
          name = "Projects"
          url  = "projects"
        [[params.footer.research.link]]
          name = "Services"
          url  = "services"

      [params.footer.social]
        title  = "Social Media"
        [[params.footer.social.link]]
          name = "Twitter"
          url  = "#"

      # Service not used not used currently
      [params.footer.service]
        title       = ""
        description = ""

