#baseURL:         https://ncar.github.io/vast/
languageCode:    en-us
title:           "VAST | Visualization and Analysis Software Team"
theme:           roxo-hugo
enableGitInfo:   true
summarylength:   25
#googleAnalitycs:

markup:
  goldmark:
    renderer:
      unsafe: true

# Site Menus
menu:
  # Navbar Menus
  nav:
    - identifier: about
      name:       About Us
      url:        about
      weight:     1
    - parent:     about
      name:       Mission
      url:        about/mission
      weight:     1
    - parent:     about
      name:       Team
      url:        /about/team
      weight:     2
    - identifier: what
      name:       What we do
      url:        /what-we-do/
      weight:     2
    - parent:     what
      name:       Software
      url:        /software/
      weight:     1
    - parent:     what
      name:       Training
      url:        /training/
      weight:     2
    - parent:     what
      name:       Projects
      url:        /projects/
      weight:     3
    - parent:     what
      name:       Services
      url:        /services/
      weight:     4
    - name:       Blog
      url:        /blog/
      weight:     3
    - name:       Publications
      url:        /publications/
      weight:     4
    - name:       Presentations
      url:        /presentations/
      weight:     5

# Site Params
params:
  logo: "images/bam-crop.png"
  dateFormat: "26 FEB 1994"
  description: "VAST is the Visualization and Analysis Software Team at the National Center for Atmospheric Research (NCAR)."
  author: "VAST"
  # googleAnalitycsID: "Your ID"
  # formspreeFormUrl : "https://formspree.io/myykjpje"
  email: "vast@ucar.edu"

  # Navbar Action Button
  navAction:
    status : true
    name   : "Get in touch"
    url    : "contact"

  # Banner Section
  banner:
    enable               : true
    background_image     : images/backgrounds/NCAR-Waves.png
    heading              : The Visualization and Analysis Software Team
    tagline              : tagline
    primary_button       : Software
    primary_button_url   : /software/
    secondary_button     : Contact Us
    secondary_button_url : /contact/

  projects:
    enable              : true
    title               : RECENT PROJECTS
    subtitle            : VAST Projects
    primary_button      : Publications
    primary_button_url  : /publications/
    secondary_button    : Presentations
    secondary_button_url: /presentations/

  training:
    background_image    : images/backgrounds/NCAR-Waves.png

  call_to_action:
    enable              : false
    background_image    : images/backgrounds/cta-background.jpg
    heading             : "Tutorials"
    tagline             : "Geoscientists are generational thinkers. We study deep into the Earth's past and make projections of its future. DART provides training materials to guide the next generation of scientists."
    primary_button      : "Submit Query"
    primary_button_url  : "contact"
    secondary_button    : "Not Convinced"
    secondary_button_url: "research"

  collab:
    enable          : true
    heading         : "Supported models"
    background_image: "images/backgrounds/NCAR-Waves.png"

  footer:
    contactInfo:
      title  : "Contact Info"
      address: "1850 Table Mesa Dr.<br>Boulder, CO 80305"
      email  : "vast@ucar.edu"

      sitemap:
        title: Sitemap
        link:
          - name: About us
            url : /about/
          - name: What we do
            url : /what-we-do/
          - name: Blog
            url : blog
          - name: Publications
            url : /publications/
          - name: Presentations
            url : /presentations/

      what-we-do:
        title: What we do
        link:
          - name: "Software"
            url : "software"
          - name: "Training"
            url : "training"
          - name: "Projects"
            url : "projects"
          - name: "Services"
            url : "services"

      social:
        title: Social Media
        link:
          - name: Twitter
          - url : "#"

      service:
        title       : ""
        description : ""

