baseURL       : https://ncar.github.io/vast/
languageCode  : en-us
title         : "VAST | Visualization and Analysis Software and Technology"
theme         : roxo-hugo
enableGitInfo : true
summarylength : 25

menu:
  nav:
    - name      : Home
      url       : ""
      weight    : 1
    - name      : About
      url       : about
      weight    : 2
    - name      : What We Do
      weight    : 3
    - name      : Blog
      url       : blog
      weight    : 4
    - name      : Contact Us
      url       : contact
      weight    : 5

# Site Params
params:
  logo: images/logos/ncar-vast-logo-navy.svg
  dateFormat: "26 FEB 1994"
  description: "VAST is the Visualization and Analysis Software Team at the National Center for Atmospheric Research (NCAR)."
  author: "VAST"
  email: "vast@ucar.edu"

  footer:
    contactInfo:
      title  : Contact Info
      address: 1850 Table Mesa Dr.<br>Boulder, CO 80305
      email  : vast@ucar.edu

    sitemap:
      title: Sitemap
      link:
        - name: About us
          url : /about/
        - name: Blog
          url : /blog/
        - name: Publications
          url : /publications/

    whatwedo:
      title: What we do
      link:
        - name: Software
          url : /software/
        - name: Training
          url : /training/
        - name: Projects
          url : /projects/
        - name: Services
          url : /services/
