baseURL       : https://jukent.github.io/geocat-hugo/
languageCode  : en-us
title         : "GeoCAT| Geoscience Community Analysis Toolkit"
theme         : ncar
enableGitInfo : true
summarylength : 25

menu:
  nav:
    - name      : About
      url       : about
      weight    : 1

    - name      : News
      url       : news
      weight    : 2

    - identifier: software
      name      : Software
      weight    : 3
    - parent    : software
      name      : Active Development Software
      url       : software
      weight    : 1
    - parent    : software
      name      : Maintenance Software
      url       : software-maintenance
      weight    : 2

    - identifier: galleries
      name      : Galleries
      weight    : 4
    - parent    : galleries
      name      : Examples
      url       : geocat-examples
      weight    : 1
    - parent    : galleries
      name      : Applications
      url       : geocat-applications
      weight    : 2
  
    - identifier: community
      name      : Community
      weight    : 6
    - parent    : community
      name      : Collaborations
      url       : collaborations
      weight    : 1
    - parent    : community
      name      : Tutorials and Presentations
      url       : talks
      weight    : 3
    - parent    : community
      name      : Internships
      url       : siparcs
      weight    : 4
  
    - name      : Feature Request
      weight    : 7
      url: https://forms.gle/6DTo3ELLri4DAGfG8

# Site Params
params:
  name: GeoCAT
  dateFormat: "26 FEB 1994"
  description: "GeoCAT is the Geoscience Community Analysis Toolkit team at the NSF National Center for Atmospheric Research (NCAR)."
  author: "GeoCAT"
  email: "geocat@ucar.edu"

  news:
    enable: true
    title: RECENT NEWS
    subtitle: Some of our most recent news

  projects:
    enable: true
    title: RECENT PROJECTS
    subtitle: Some of our most recent projects

  footer:
    contactInfo:
      title  : Contact Info
      address: 1850 Table Mesa Dr.<br>Boulder, CO 80305
      email  : geocat@ucar.edu

    sitemap:
      title: Sitemap
      column:
        - link:
          - name: About us
            url : about
          - name: News
            url : news
          - name: Presentations
            url: presentations
          - name: Internships
            url : siparcs
        - link:
          - name: Software
            url : software
          - name: Education
            url : education
          - name: Services
            url : services
          - name: R&D
            url : projects

