name: Update SIParCS Metrics

on:
  push:
    branches:
      - main
    paths:
      - 'data/siparcs.yml'
    
jobs:
  update_metrics:
    runs-on: 'ubuntu-20.04'
    steps:
    - uses: actions/checkout@v3
      with:
        ref: 'main'
  
    - name: Install dependencies
      run: |
        python -m pip install pip --upgrade
        python -m pip install ruamel.yaml pre-commit
          
    - name: Update publications metrics
      shell: python
      run: |
        from ruamel.yaml import YAML
        yaml = YAML()

        siparcs_file = 'data/siparcs.yml'
        metrics_file = 'data/metrics.yml'
          
        with open(siparcs_file) as f:
          siparcs_dict = yaml.load(f)
        number = len(siparcs_dict['items'])

        with open(metrics_file, 'r+') as f:
          metrics_dict = yaml.load(f)
        metrics_dict['counter_item'][3]["number"] = number
        with open(metrics_file, 'w') as f:
          yaml.dump(metrics_dict, f)

    - name: Commit and push changes
      run: |
        git config --global user.name '${{ github.actor }}'
        git config --global user.email '<${{ github.actor }}@users.noreply.github.com>'
        git remote set-url origin https://x-access-token:${{ secrets.VAST_METRICS }}@github.com/NCAR/vast
        git add data/metrics.yml
        git commit -m "Update metrics.yml from changes to siparcs.yml"
        git push -u origin HEAD
